export type Tier = "mega" | "large" | "mid";
export type CarbonIntensity = "very_low" | "low" | "medium" | "high" | "very_high";

export interface PoolHolding {
  ticker: string;
  name: string;
  sector: string;
  industry: string;
  themes: string[];
  valuationScore: number;    // 0-100, higher = more attractive valuation
  momentumScore: number;     // 0-100, higher = stronger price momentum
  qualityScore: number;      // 0-100, ROIC + margin quality
  lowVolScore: number;       // 0-100, higher = lower beta/volatility
  profitabilityScore: number;// 0-100, FCF + earnings stability
  dividendYield: number;     // annual %
  dividendGrowth5Y: number;  // 5-year CAGR %
  payoutRatio: number;       // %
  beta: number;
  marketCapB: number;        // USD billions
  tier: Tier;
  peRatio: number;
  revenueGrowthYoY: number;  // TTM %
  fcfMargin: number;         // %
  grossMargin: number;       // %
  roe: number;               // %
  debtToEquity: number;
  esgScore: number;          // 0-100
  carbonIntensity: CarbonIntensity;
  country: string;
}

export const holdingPool: PoolHolding[] = [
  // ─── AI / SEMICONDUCTOR ───────────────────────────────────────────────────
  {
    ticker: "NVDA", name: "NVIDIA Corporation", sector: "Information Technology", industry: "Semiconductors",
    themes: ["ai", "semiconductor", "infrastructure", "growth", "momentum"],
    valuationScore: 42, momentumScore: 96, qualityScore: 92, lowVolScore: 22, profitabilityScore: 91,
    dividendYield: 0.03, dividendGrowth5Y: 5, payoutRatio: 1, beta: 1.85, marketCapB: 2900, tier: "mega",
    peRatio: 68, revenueGrowthYoY: 122, fcfMargin: 51, grossMargin: 75, roe: 124, debtToEquity: 0.4,
    esgScore: 62, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "MSFT", name: "Microsoft Corporation", sector: "Information Technology", industry: "Software",
    themes: ["ai", "cloud", "software", "quality", "dividend", "dividend_growth", "growth", "infrastructure"],
    valuationScore: 62, momentumScore: 82, qualityScore: 97, lowVolScore: 48, profitabilityScore: 94,
    dividendYield: 0.7, dividendGrowth5Y: 11, payoutRatio: 25, beta: 0.9, marketCapB: 3100, tier: "mega",
    peRatio: 35, revenueGrowthYoY: 17, fcfMargin: 34, grossMargin: 69, roe: 39, debtToEquity: 0.3,
    esgScore: 81, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "AAPL", name: "Apple Inc.", sector: "Information Technology", industry: "Consumer Electronics",
    themes: ["quality", "dividend", "dividend_growth", "consumer", "momentum", "low_volatility"],
    valuationScore: 58, momentumScore: 74, qualityScore: 95, lowVolScore: 55, profitabilityScore: 93,
    dividendYield: 0.5, dividendGrowth5Y: 6, payoutRatio: 15, beta: 1.2, marketCapB: 3200, tier: "mega",
    peRatio: 31, revenueGrowthYoY: 4, fcfMargin: 26, grossMargin: 45, roe: 171, debtToEquity: 1.8,
    esgScore: 78, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "AVGO", name: "Broadcom Inc.", sector: "Information Technology", industry: "Semiconductors",
    themes: ["ai", "semiconductor", "infrastructure", "dividend", "dividend_growth", "momentum"],
    valuationScore: 68, momentumScore: 87, qualityScore: 89, lowVolScore: 38, profitabilityScore: 86,
    dividendYield: 1.4, dividendGrowth5Y: 14, payoutRatio: 42, beta: 1.25, marketCapB: 780, tier: "mega",
    peRatio: 30, revenueGrowthYoY: 51, fcfMargin: 46, grossMargin: 62, roe: 91, debtToEquity: 1.2,
    esgScore: 64, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "AMD", name: "Advanced Micro Devices", sector: "Information Technology", industry: "Semiconductors",
    themes: ["ai", "semiconductor", "growth", "momentum"],
    valuationScore: 52, momentumScore: 78, qualityScore: 82, lowVolScore: 26, profitabilityScore: 76,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.75, marketCapB: 262, tier: "large",
    peRatio: 44, revenueGrowthYoY: 24, fcfMargin: 22, grossMargin: 50, roe: 5, debtToEquity: 0.3,
    esgScore: 68, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "TSM", name: "Taiwan Semiconductor", sector: "Information Technology", industry: "Semiconductor Manufacturing",
    themes: ["ai", "semiconductor", "infrastructure", "quality", "value", "momentum"],
    valuationScore: 74, momentumScore: 84, qualityScore: 94, lowVolScore: 32, profitabilityScore: 90,
    dividendYield: 1.2, dividendGrowth5Y: 8, payoutRatio: 32, beta: 1.15, marketCapB: 960, tier: "mega",
    peRatio: 26, revenueGrowthYoY: 38, fcfMargin: 40, grossMargin: 54, roe: 31, debtToEquity: 0.2,
    esgScore: 72, carbonIntensity: "low", country: "Taiwan",
  },
  {
    ticker: "MU", name: "Micron Technology", sector: "Information Technology", industry: "Memory & Storage",
    themes: ["ai", "semiconductor", "infrastructure", "value", "momentum"],
    valuationScore: 71, momentumScore: 82, qualityScore: 78, lowVolScore: 24, profitabilityScore: 74,
    dividendYield: 0.4, dividendGrowth5Y: 4, payoutRatio: 6, beta: 1.5, marketCapB: 123, tier: "large",
    peRatio: 16, revenueGrowthYoY: 93, fcfMargin: 18, grossMargin: 32, roe: 10, debtToEquity: 0.3,
    esgScore: 66, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "ANET", name: "Arista Networks", sector: "Information Technology", industry: "Data Center Networking",
    themes: ["ai", "cloud", "infrastructure", "quality", "momentum"],
    valuationScore: 60, momentumScore: 82, qualityScore: 90, lowVolScore: 36, profitabilityScore: 88,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.2, marketCapB: 132, tier: "large",
    peRatio: 48, revenueGrowthYoY: 22, fcfMargin: 37, grossMargin: 64, roe: 34, debtToEquity: 0,
    esgScore: 70, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "SMCI", name: "Super Micro Computer", sector: "Information Technology", industry: "AI Server Systems",
    themes: ["ai", "infrastructure", "value", "growth"],
    valuationScore: 62, momentumScore: 71, qualityScore: 68, lowVolScore: 18, profitabilityScore: 65,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 2.1, marketCapB: 48, tier: "large",
    peRatio: 19, revenueGrowthYoY: 37, fcfMargin: 8, grossMargin: 15, roe: 21, debtToEquity: 0.5,
    esgScore: 45, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "ORCL", name: "Oracle Corporation", sector: "Information Technology", industry: "Cloud & Database",
    themes: ["ai", "cloud", "software", "dividend", "momentum"],
    valuationScore: 62, momentumScore: 80, qualityScore: 86, lowVolScore: 44, profitabilityScore: 84,
    dividendYield: 1.1, dividendGrowth5Y: 13, payoutRatio: 36, beta: 0.9, marketCapB: 427, tier: "mega",
    peRatio: 34, revenueGrowthYoY: 9, fcfMargin: 34, grossMargin: 71, roe: 310, debtToEquity: 14.2,
    esgScore: 58, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "QCOM", name: "Qualcomm Inc.", sector: "Information Technology", industry: "Semiconductors",
    themes: ["semiconductor", "ai", "dividend", "value"],
    valuationScore: 72, momentumScore: 73, qualityScore: 82, lowVolScore: 44, profitabilityScore: 80,
    dividendYield: 2.2, dividendGrowth5Y: 7, payoutRatio: 37, beta: 1.15, marketCapB: 168, tier: "large",
    peRatio: 17, revenueGrowthYoY: 9, fcfMargin: 28, grossMargin: 56, roe: 41, debtToEquity: 0.5,
    esgScore: 72, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "ARM", name: "Arm Holdings", sector: "Information Technology", industry: "Semiconductors",
    themes: ["ai", "semiconductor", "growth", "momentum"],
    valuationScore: 38, momentumScore: 88, qualityScore: 84, lowVolScore: 20, profitabilityScore: 76,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.6, marketCapB: 145, tier: "large",
    peRatio: 175, revenueGrowthYoY: 49, fcfMargin: 38, grossMargin: 96, roe: 21, debtToEquity: 0.1,
    esgScore: 74, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "MRVL", name: "Marvell Technology", sector: "Information Technology", industry: "Semiconductors",
    themes: ["ai", "semiconductor", "infrastructure", "growth", "momentum"],
    valuationScore: 55, momentumScore: 84, qualityScore: 78, lowVolScore: 26, profitabilityScore: 72,
    dividendYield: 0.3, dividendGrowth5Y: 3, payoutRatio: 23, beta: 1.7, marketCapB: 81, tier: "large",
    peRatio: 78, revenueGrowthYoY: 9, fcfMargin: 24, grossMargin: 47, roe: 5, debtToEquity: 0.5,
    esgScore: 64, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "PLTR", name: "Palantir Technologies", sector: "Information Technology", industry: "AI Software",
    themes: ["ai", "software", "growth", "momentum"],
    valuationScore: 32, momentumScore: 90, qualityScore: 72, lowVolScore: 18, profitabilityScore: 58,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 2.0, marketCapB: 220, tier: "large",
    peRatio: 260, revenueGrowthYoY: 36, fcfMargin: 29, grossMargin: 81, roe: 11, debtToEquity: 0,
    esgScore: 55, carbonIntensity: "very_low", country: "US",
  },
  // ─── CLOUD / SOFTWARE ────────────────────────────────────────────────────
  {
    ticker: "GOOGL", name: "Alphabet Inc.", sector: "Communication Services", industry: "Cloud & AI",
    themes: ["ai", "cloud", "software", "quality", "value", "growth"],
    valuationScore: 69, momentumScore: 71, qualityScore: 92, lowVolScore: 42, profitabilityScore: 88,
    dividendYield: 0.4, dividendGrowth5Y: 0, payoutRatio: 10, beta: 1.05, marketCapB: 2100, tier: "mega",
    peRatio: 24, revenueGrowthYoY: 15, fcfMargin: 19, grossMargin: 57, roe: 28, debtToEquity: 0.1,
    esgScore: 72, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "META", name: "Meta Platforms Inc.", sector: "Communication Services", industry: "AI & Social",
    themes: ["ai", "cloud", "growth", "momentum", "value"],
    valuationScore: 66, momentumScore: 79, qualityScore: 88, lowVolScore: 36, profitabilityScore: 87,
    dividendYield: 0.4, dividendGrowth5Y: 0, payoutRatio: 11, beta: 1.3, marketCapB: 1400, tier: "mega",
    peRatio: 28, revenueGrowthYoY: 22, fcfMargin: 34, grossMargin: 81, roe: 37, debtToEquity: 0.1,
    esgScore: 60, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary", industry: "Cloud & E-Commerce",
    themes: ["ai", "cloud", "infrastructure", "growth", "quality"],
    valuationScore: 63, momentumScore: 77, qualityScore: 90, lowVolScore: 38, profitabilityScore: 85,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.15, marketCapB: 1900, tier: "mega",
    peRatio: 42, revenueGrowthYoY: 13, fcfMargin: 8, grossMargin: 47, roe: 22, debtToEquity: 0.7,
    esgScore: 68, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "CRM", name: "Salesforce Inc.", sector: "Information Technology", industry: "Enterprise Software",
    themes: ["software", "cloud", "ai", "quality"],
    valuationScore: 52, momentumScore: 69, qualityScore: 82, lowVolScore: 38, profitabilityScore: 76,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.2, marketCapB: 278, tier: "large",
    peRatio: 42, revenueGrowthYoY: 9, fcfMargin: 22, grossMargin: 77, roe: 9, debtToEquity: 0.2,
    esgScore: 76, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "NOW", name: "ServiceNow Inc.", sector: "Information Technology", industry: "Enterprise Software",
    themes: ["software", "cloud", "ai", "quality", "growth"],
    valuationScore: 44, momentumScore: 78, qualityScore: 88, lowVolScore: 34, profitabilityScore: 80,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.15, marketCapB: 196, tier: "large",
    peRatio: 55, revenueGrowthYoY: 21, fcfMargin: 26, grossMargin: 79, roe: 14, debtToEquity: 0.3,
    esgScore: 78, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "ADBE", name: "Adobe Inc.", sector: "Information Technology", industry: "Software",
    themes: ["software", "ai", "quality", "low_volatility"],
    valuationScore: 56, momentumScore: 62, qualityScore: 90, lowVolScore: 48, profitabilityScore: 86,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.1, marketCapB: 210, tier: "large",
    peRatio: 40, revenueGrowthYoY: 11, fcfMargin: 38, grossMargin: 88, roe: 36, debtToEquity: 0.5,
    esgScore: 80, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "PANW", name: "Palo Alto Networks", sector: "Information Technology", industry: "Cybersecurity",
    themes: ["software", "cloud", "security", "growth"],
    valuationScore: 46, momentumScore: 74, qualityScore: 82, lowVolScore: 32, profitabilityScore: 74,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.1, marketCapB: 127, tier: "large",
    peRatio: 56, revenueGrowthYoY: 16, fcfMargin: 36, grossMargin: 75, roe: 22, debtToEquity: 0.6,
    esgScore: 72, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "INTU", name: "Intuit Inc.", sector: "Information Technology", industry: "Financial Software",
    themes: ["software", "fintech", "quality", "dividend_growth"],
    valuationScore: 54, momentumScore: 72, qualityScore: 88, lowVolScore: 46, profitabilityScore: 84,
    dividendYield: 0.6, dividendGrowth5Y: 16, payoutRatio: 24, beta: 1.05, marketCapB: 172, tier: "large",
    peRatio: 49, revenueGrowthYoY: 13, fcfMargin: 28, grossMargin: 79, roe: 19, debtToEquity: 0.6,
    esgScore: 76, carbonIntensity: "very_low", country: "US",
  },
  // ─── HEALTHCARE ──────────────────────────────────────────────────────────
  {
    ticker: "LLY", name: "Eli Lilly & Co.", sector: "Health Care", industry: "Pharmaceuticals",
    themes: ["healthcare", "biotech", "growth", "momentum", "quality"],
    valuationScore: 36, momentumScore: 88, qualityScore: 90, lowVolScore: 38, profitabilityScore: 88,
    dividendYield: 0.6, dividendGrowth5Y: 15, payoutRatio: 24, beta: 0.4, marketCapB: 830, tier: "mega",
    peRatio: 78, revenueGrowthYoY: 58, fcfMargin: 34, grossMargin: 76, roe: 74, debtToEquity: 2.0,
    esgScore: 74, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "UNH", name: "UnitedHealth Group", sector: "Health Care", industry: "Managed Care",
    themes: ["healthcare", "quality", "dividend_growth", "low_volatility", "value"],
    valuationScore: 66, momentumScore: 62, qualityScore: 90, lowVolScore: 62, profitabilityScore: 88,
    dividendYield: 1.7, dividendGrowth5Y: 14, payoutRatio: 42, beta: 0.6, marketCapB: 490, tier: "mega",
    peRatio: 22, revenueGrowthYoY: 8, fcfMargin: 9, grossMargin: 26, roe: 29, debtToEquity: 0.7,
    esgScore: 70, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "JNJ", name: "Johnson & Johnson", sector: "Health Care", industry: "Pharmaceuticals",
    themes: ["healthcare", "dividend", "dividend_growth", "defensive", "low_volatility", "quality", "value"],
    valuationScore: 74, momentumScore: 44, qualityScore: 88, lowVolScore: 76, profitabilityScore: 86,
    dividendYield: 3.1, dividendGrowth5Y: 5, payoutRatio: 68, beta: 0.55, marketCapB: 390, tier: "mega",
    peRatio: 16, revenueGrowthYoY: 5, fcfMargin: 22, grossMargin: 66, roe: 22, debtToEquity: 0.4,
    esgScore: 82, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "ABBV", name: "AbbVie Inc.", sector: "Health Care", industry: "Pharmaceuticals",
    themes: ["healthcare", "dividend", "dividend_growth", "value", "income"],
    valuationScore: 68, momentumScore: 62, qualityScore: 80, lowVolScore: 56, profitabilityScore: 82,
    dividendYield: 3.4, dividendGrowth5Y: 8, payoutRatio: 74, beta: 0.6, marketCapB: 312, tier: "large",
    peRatio: 14, revenueGrowthYoY: 4, fcfMargin: 36, grossMargin: 70, roe: 0, debtToEquity: 12.8,
    esgScore: 66, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "ISRG", name: "Intuitive Surgical", sector: "Health Care", industry: "Medical Devices",
    themes: ["healthcare", "quality", "growth", "momentum", "low_volatility"],
    valuationScore: 46, momentumScore: 80, qualityScore: 92, lowVolScore: 58, profitabilityScore: 88,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 0.9, marketCapB: 192, tier: "large",
    peRatio: 64, revenueGrowthYoY: 18, fcfMargin: 22, grossMargin: 68, roe: 18, debtToEquity: 0,
    esgScore: 76, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "AMGN", name: "Amgen Inc.", sector: "Health Care", industry: "Biotechnology",
    themes: ["healthcare", "biotech", "dividend", "dividend_growth", "value", "income"],
    valuationScore: 62, momentumScore: 56, qualityScore: 82, lowVolScore: 62, profitabilityScore: 84,
    dividendYield: 3.3, dividendGrowth5Y: 11, payoutRatio: 72, beta: 0.5, marketCapB: 164, tier: "large",
    peRatio: 16, revenueGrowthYoY: 24, fcfMargin: 38, grossMargin: 78, roe: 86, debtToEquity: 6.0,
    esgScore: 72, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Health Care", industry: "Biotechnology",
    themes: ["healthcare", "biotech", "quality", "value"],
    valuationScore: 64, momentumScore: 60, qualityScore: 88, lowVolScore: 52, profitabilityScore: 86,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 0.5, marketCapB: 84, tier: "large",
    peRatio: 18, revenueGrowthYoY: 14, fcfMargin: 42, grossMargin: 86, roe: 20, debtToEquity: 0.1,
    esgScore: 70, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Health Care", industry: "Biotechnology",
    themes: ["healthcare", "biotech", "quality", "growth"],
    valuationScore: 58, momentumScore: 68, qualityScore: 90, lowVolScore: 56, profitabilityScore: 88,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 0.55, marketCapB: 126, tier: "large",
    peRatio: 26, revenueGrowthYoY: 12, fcfMargin: 46, grossMargin: 88, roe: 30, debtToEquity: 0,
    esgScore: 74, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "MRK", name: "Merck & Co.", sector: "Health Care", industry: "Pharmaceuticals",
    themes: ["healthcare", "dividend", "value", "defensive", "income"],
    valuationScore: 66, momentumScore: 52, qualityScore: 82, lowVolScore: 64, profitabilityScore: 82,
    dividendYield: 2.6, dividendGrowth5Y: 8, payoutRatio: 56, beta: 0.5, marketCapB: 268, tier: "large",
    peRatio: 13, revenueGrowthYoY: 11, fcfMargin: 24, grossMargin: 74, roe: 42, debtToEquity: 0.8,
    esgScore: 76, carbonIntensity: "low", country: "US",
  },
  // ─── CONSUMER STAPLES / DIVIDEND PAYERS ──────────────────────────────────
  {
    ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples", industry: "Household Products",
    themes: ["staples", "defensive", "dividend", "dividend_growth", "quality", "low_volatility", "income"],
    valuationScore: 60, momentumScore: 54, qualityScore: 88, lowVolScore: 80, profitabilityScore: 88,
    dividendYield: 2.4, dividendGrowth5Y: 5, payoutRatio: 58, beta: 0.45, marketCapB: 376, tier: "mega",
    peRatio: 26, revenueGrowthYoY: 3, fcfMargin: 18, grossMargin: 51, roe: 32, debtToEquity: 0.9,
    esgScore: 82, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "KO", name: "The Coca-Cola Company", sector: "Consumer Staples", industry: "Beverages",
    themes: ["staples", "defensive", "dividend", "dividend_growth", "quality", "low_volatility", "income", "value"],
    valuationScore: 62, momentumScore: 48, qualityScore: 82, lowVolScore: 82, profitabilityScore: 84,
    dividendYield: 3.2, dividendGrowth5Y: 4, payoutRatio: 74, beta: 0.55, marketCapB: 264, tier: "large",
    peRatio: 24, revenueGrowthYoY: 4, fcfMargin: 22, grossMargin: 60, roe: 42, debtToEquity: 1.7,
    esgScore: 78, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples", industry: "Food & Beverages",
    themes: ["staples", "defensive", "dividend", "dividend_growth", "quality", "low_volatility", "income"],
    valuationScore: 58, momentumScore: 46, qualityScore: 84, lowVolScore: 78, profitabilityScore: 84,
    dividendYield: 3.0, dividendGrowth5Y: 7, payoutRatio: 68, beta: 0.5, marketCapB: 224, tier: "large",
    peRatio: 24, revenueGrowthYoY: 2, fcfMargin: 12, grossMargin: 54, roe: 54, debtToEquity: 2.3,
    esgScore: 80, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Staples", industry: "Retail",
    themes: ["staples", "defensive", "dividend", "dividend_growth", "quality", "low_volatility"],
    valuationScore: 56, momentumScore: 70, qualityScore: 86, lowVolScore: 72, profitabilityScore: 82,
    dividendYield: 1.3, dividendGrowth5Y: 4, payoutRatio: 34, beta: 0.55, marketCapB: 786, tier: "mega",
    peRatio: 42, revenueGrowthYoY: 6, fcfMargin: 3, grossMargin: 24, roe: 22, debtToEquity: 0.7,
    esgScore: 74, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "COST", name: "Costco Wholesale", sector: "Consumer Staples", industry: "Retail",
    themes: ["staples", "quality", "dividend_growth", "low_volatility", "consumer"],
    valuationScore: 44, momentumScore: 72, qualityScore: 90, lowVolScore: 68, profitabilityScore: 86,
    dividendYield: 0.5, dividendGrowth5Y: 12, payoutRatio: 28, beta: 0.75, marketCapB: 428, tier: "mega",
    peRatio: 58, revenueGrowthYoY: 6, fcfMargin: 3, grossMargin: 13, roe: 31, debtToEquity: 0.4,
    esgScore: 78, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "MCD", name: "McDonald's Corporation", sector: "Consumer Discretionary", industry: "Restaurants",
    themes: ["consumer", "defensive", "dividend", "dividend_growth", "quality", "low_volatility", "income"],
    valuationScore: 58, momentumScore: 52, qualityScore: 86, lowVolScore: 74, profitabilityScore: 88,
    dividendYield: 2.3, dividendGrowth5Y: 8, payoutRatio: 58, beta: 0.7, marketCapB: 212, tier: "large",
    peRatio: 26, revenueGrowthYoY: 2, fcfMargin: 26, grossMargin: 57, roe: 0, debtToEquity: 0,
    esgScore: 64, carbonIntensity: "high", country: "US",
  },
  {
    ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples", industry: "Household Products",
    themes: ["staples", "defensive", "dividend", "dividend_growth", "low_volatility", "income"],
    valuationScore: 58, momentumScore: 50, qualityScore: 82, lowVolScore: 82, profitabilityScore: 82,
    dividendYield: 2.4, dividendGrowth5Y: 4, payoutRatio: 62, beta: 0.4, marketCapB: 64, tier: "large",
    peRatio: 28, revenueGrowthYoY: 4, fcfMargin: 14, grossMargin: 58, roe: 0, debtToEquity: 0,
    esgScore: 80, carbonIntensity: "low", country: "US",
  },
  // ─── FINANCIALS ──────────────────────────────────────────────────────────
  {
    ticker: "V", name: "Visa Inc.", sector: "Financials", industry: "Payments",
    themes: ["fintech", "quality", "dividend_growth", "low_volatility", "value", "financial"],
    valuationScore: 64, momentumScore: 72, qualityScore: 96, lowVolScore: 60, profitabilityScore: 92,
    dividendYield: 0.8, dividendGrowth5Y: 18, payoutRatio: 24, beta: 0.95, marketCapB: 556, tier: "mega",
    peRatio: 30, revenueGrowthYoY: 10, fcfMargin: 62, grossMargin: 80, roe: 50, debtToEquity: 0.6,
    esgScore: 76, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "MA", name: "Mastercard Inc.", sector: "Financials", industry: "Payments",
    themes: ["fintech", "quality", "dividend_growth", "value", "growth", "financial"],
    valuationScore: 62, momentumScore: 74, qualityScore: 96, lowVolScore: 58, profitabilityScore: 92,
    dividendYield: 0.6, dividendGrowth5Y: 16, payoutRatio: 20, beta: 1.0, marketCapB: 484, tier: "mega",
    peRatio: 38, revenueGrowthYoY: 11, fcfMargin: 52, grossMargin: 79, roe: 194, debtToEquity: 2.0,
    esgScore: 76, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "JPM", name: "JPMorgan Chase", sector: "Financials", industry: "Banks",
    themes: ["financial", "dividend", "dividend_growth", "value", "quality"],
    valuationScore: 72, momentumScore: 70, qualityScore: 84, lowVolScore: 50, profitabilityScore: 84,
    dividendYield: 2.2, dividendGrowth5Y: 8, payoutRatio: 30, beta: 1.1, marketCapB: 636, tier: "mega",
    peRatio: 13, revenueGrowthYoY: 18, fcfMargin: 35, grossMargin: 65, roe: 17, debtToEquity: 1.3,
    esgScore: 68, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "BRK.B", name: "Berkshire Hathaway B", sector: "Financials", industry: "Conglomerate",
    themes: ["financial", "value", "quality", "low_volatility", "defensive"],
    valuationScore: 74, momentumScore: 62, qualityScore: 88, lowVolScore: 62, profitabilityScore: 86,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 0.85, marketCapB: 960, tier: "mega",
    peRatio: 22, revenueGrowthYoY: 8, fcfMargin: 18, grossMargin: 30, roe: 12, debtToEquity: 0.4,
    esgScore: 66, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "BAC", name: "Bank of America", sector: "Financials", industry: "Banks",
    themes: ["financial", "dividend", "value", "income"],
    valuationScore: 70, momentumScore: 66, qualityScore: 76, lowVolScore: 46, profitabilityScore: 76,
    dividendYield: 2.5, dividendGrowth5Y: 6, payoutRatio: 36, beta: 1.3, marketCapB: 340, tier: "mega",
    peRatio: 12, revenueGrowthYoY: 14, fcfMargin: 30, grossMargin: 55, roe: 10, debtToEquity: 1.2,
    esgScore: 70, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "CB", name: "Chubb Limited", sector: "Financials", industry: "Insurance",
    themes: ["financial", "dividend", "dividend_growth", "value", "low_volatility"],
    valuationScore: 72, momentumScore: 60, qualityScore: 84, lowVolScore: 66, profitabilityScore: 82,
    dividendYield: 1.5, dividendGrowth5Y: 9, payoutRatio: 30, beta: 0.7, marketCapB: 112, tier: "large",
    peRatio: 14, revenueGrowthYoY: 18, fcfMargin: 22, grossMargin: 32, roe: 14, debtToEquity: 0.3,
    esgScore: 70, carbonIntensity: "very_low", country: "US",
  },
  // ─── ENERGY ──────────────────────────────────────────────────────────────
  {
    ticker: "CVX", name: "Chevron Corporation", sector: "Energy", industry: "Oil & Gas",
    themes: ["energy", "dividend", "dividend_growth", "value", "income"],
    valuationScore: 76, momentumScore: 52, qualityScore: 78, lowVolScore: 56, profitabilityScore: 78,
    dividendYield: 4.2, dividendGrowth5Y: 7, payoutRatio: 60, beta: 1.0, marketCapB: 284, tier: "mega",
    peRatio: 14, revenueGrowthYoY: -4, fcfMargin: 12, grossMargin: 42, roe: 12, debtToEquity: 0.2,
    esgScore: 44, carbonIntensity: "very_high", country: "US",
  },
  {
    ticker: "XOM", name: "Exxon Mobil", sector: "Energy", industry: "Oil & Gas",
    themes: ["energy", "dividend", "value", "income"],
    valuationScore: 74, momentumScore: 56, qualityScore: 76, lowVolScore: 54, profitabilityScore: 76,
    dividendYield: 3.6, dividendGrowth5Y: 4, payoutRatio: 58, beta: 1.0, marketCapB: 468, tier: "mega",
    peRatio: 13, revenueGrowthYoY: -3, fcfMargin: 10, grossMargin: 36, roe: 14, debtToEquity: 0.2,
    esgScore: 40, carbonIntensity: "very_high", country: "US",
  },
  {
    ticker: "COP", name: "ConocoPhillips", sector: "Energy", industry: "Oil & Gas",
    themes: ["energy", "dividend", "value"],
    valuationScore: 74, momentumScore: 58, qualityScore: 74, lowVolScore: 50, profitabilityScore: 76,
    dividendYield: 3.0, dividendGrowth5Y: 10, payoutRatio: 46, beta: 1.05, marketCapB: 128, tier: "large",
    peRatio: 12, revenueGrowthYoY: -2, fcfMargin: 18, grossMargin: 54, roe: 18, debtToEquity: 0.3,
    esgScore: 46, carbonIntensity: "very_high", country: "US",
  },
  {
    ticker: "LIN", name: "Linde plc", sector: "Materials", industry: "Industrial Gases",
    themes: ["industrial", "quality", "dividend_growth", "low_volatility", "clean_energy"],
    valuationScore: 62, momentumScore: 68, qualityScore: 90, lowVolScore: 66, profitabilityScore: 88,
    dividendYield: 1.3, dividendGrowth5Y: 8, payoutRatio: 42, beta: 0.75, marketCapB: 212, tier: "large",
    peRatio: 34, revenueGrowthYoY: 5, fcfMargin: 18, grossMargin: 46, roe: 18, debtToEquity: 0.4,
    esgScore: 74, carbonIntensity: "medium", country: "US",
  },
  // ─── CLEAN ENERGY ────────────────────────────────────────────────────────
  {
    ticker: "NEE", name: "NextEra Energy", sector: "Utilities", industry: "Renewables",
    themes: ["clean_energy", "utilities", "dividend", "dividend_growth", "low_volatility", "infrastructure"],
    valuationScore: 56, momentumScore: 64, qualityScore: 82, lowVolScore: 74, profitabilityScore: 78,
    dividendYield: 2.9, dividendGrowth5Y: 10, payoutRatio: 66, beta: 0.6, marketCapB: 148, tier: "large",
    peRatio: 24, revenueGrowthYoY: 9, fcfMargin: 12, grossMargin: 44, roe: 12, debtToEquity: 1.3,
    esgScore: 84, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "CEG", name: "Constellation Energy", sector: "Utilities", industry: "Nuclear & Renewables",
    themes: ["clean_energy", "ai", "infrastructure", "momentum"],
    valuationScore: 52, momentumScore: 86, qualityScore: 76, lowVolScore: 46, profitabilityScore: 74,
    dividendYield: 0.8, dividendGrowth5Y: 0, payoutRatio: 16, beta: 0.8, marketCapB: 88, tier: "large",
    peRatio: 28, revenueGrowthYoY: 24, fcfMargin: 14, grossMargin: 28, roe: 14, debtToEquity: 0.6,
    esgScore: 82, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "ENPH", name: "Enphase Energy", sector: "Information Technology", industry: "Solar Microinverters",
    themes: ["clean_energy", "growth"],
    valuationScore: 44, momentumScore: 58, qualityScore: 72, lowVolScore: 22, profitabilityScore: 70,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.8, marketCapB: 17, tier: "mid",
    peRatio: 24, revenueGrowthYoY: -46, fcfMargin: 24, grossMargin: 44, roe: 28, debtToEquity: 0.7,
    esgScore: 84, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "FSLR", name: "First Solar Inc.", sector: "Information Technology", industry: "Solar Panels",
    themes: ["clean_energy", "value", "growth"],
    valuationScore: 64, momentumScore: 62, qualityScore: 72, lowVolScore: 32, profitabilityScore: 70,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.4, marketCapB: 19, tier: "mid",
    peRatio: 16, revenueGrowthYoY: 26, fcfMargin: 16, grossMargin: 46, roe: 14, debtToEquity: 0.2,
    esgScore: 88, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "AES", name: "AES Corporation", sector: "Utilities", industry: "Clean Electricity",
    themes: ["clean_energy", "utilities", "dividend", "income"],
    valuationScore: 68, momentumScore: 46, qualityScore: 68, lowVolScore: 60, profitabilityScore: 66,
    dividendYield: 4.2, dividendGrowth5Y: 5, payoutRatio: 80, beta: 0.9, marketCapB: 12, tier: "mid",
    peRatio: 18, revenueGrowthYoY: 4, fcfMargin: 8, grossMargin: 22, roe: 10, debtToEquity: 3.2,
    esgScore: 80, carbonIntensity: "low", country: "US",
  },
  // ─── UTILITIES ───────────────────────────────────────────────────────────
  {
    ticker: "SO", name: "Southern Company", sector: "Utilities", industry: "Electric Utilities",
    themes: ["utilities", "dividend", "defensive", "low_volatility", "income"],
    valuationScore: 58, momentumScore: 46, qualityScore: 76, lowVolScore: 80, profitabilityScore: 74,
    dividendYield: 3.9, dividendGrowth5Y: 4, payoutRatio: 82, beta: 0.4, marketCapB: 82, tier: "large",
    peRatio: 22, revenueGrowthYoY: 6, fcfMargin: 8, grossMargin: 34, roe: 11, debtToEquity: 1.6,
    esgScore: 66, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "AEP", name: "American Electric Power", sector: "Utilities", industry: "Electric Utilities",
    themes: ["utilities", "dividend", "defensive", "low_volatility", "income", "clean_energy"],
    valuationScore: 60, momentumScore: 48, qualityScore: 74, lowVolScore: 80, profitabilityScore: 72,
    dividendYield: 4.1, dividendGrowth5Y: 5, payoutRatio: 82, beta: 0.4, marketCapB: 46, tier: "large",
    peRatio: 20, revenueGrowthYoY: 10, fcfMargin: 6, grossMargin: 28, roe: 9, debtToEquity: 1.7,
    esgScore: 64, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "DUK", name: "Duke Energy", sector: "Utilities", industry: "Electric Utilities",
    themes: ["utilities", "dividend", "defensive", "low_volatility", "income"],
    valuationScore: 56, momentumScore: 44, qualityScore: 74, lowVolScore: 82, profitabilityScore: 72,
    dividendYield: 4.2, dividendGrowth5Y: 3, payoutRatio: 84, beta: 0.35, marketCapB: 74, tier: "large",
    peRatio: 20, revenueGrowthYoY: 7, fcfMargin: 5, grossMargin: 26, roe: 8, debtToEquity: 1.6,
    esgScore: 64, carbonIntensity: "medium", country: "US",
  },
  // ─── TELECOM / TECH INFRASTRUCTURE ───────────────────────────────────────
  {
    ticker: "TXN", name: "Texas Instruments", sector: "Information Technology", industry: "Analog Semiconductors",
    themes: ["semiconductor", "dividend", "dividend_growth", "quality", "income", "value"],
    valuationScore: 62, momentumScore: 58, qualityScore: 86, lowVolScore: 60, profitabilityScore: 84,
    dividendYield: 3.0, dividendGrowth5Y: 14, payoutRatio: 80, beta: 1.05, marketCapB: 172, tier: "large",
    peRatio: 34, revenueGrowthYoY: -10, fcfMargin: 28, grossMargin: 65, roe: 42, debtToEquity: 0.9,
    esgScore: 74, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "CSCO", name: "Cisco Systems", sector: "Information Technology", industry: "Networking",
    themes: ["infrastructure", "dividend", "dividend_growth", "value", "income", "low_volatility"],
    valuationScore: 68, momentumScore: 58, qualityScore: 82, lowVolScore: 66, profitabilityScore: 82,
    dividendYield: 3.2, dividendGrowth5Y: 5, payoutRatio: 62, beta: 0.8, marketCapB: 238, tier: "large",
    peRatio: 17, revenueGrowthYoY: 5, fcfMargin: 26, grossMargin: 65, roe: 32, debtToEquity: 0.4,
    esgScore: 78, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "T", name: "AT&T Inc.", sector: "Communication Services", industry: "Telecom",
    themes: ["telecom", "dividend", "value", "income", "defensive"],
    valuationScore: 72, momentumScore: 44, qualityScore: 64, lowVolScore: 68, profitabilityScore: 64,
    dividendYield: 6.8, dividendGrowth5Y: 0, payoutRatio: 80, beta: 0.6, marketCapB: 126, tier: "large",
    peRatio: 11, revenueGrowthYoY: 1, fcfMargin: 12, grossMargin: 58, roe: 10, debtToEquity: 1.0,
    esgScore: 60, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "VZ", name: "Verizon Communications", sector: "Communication Services", industry: "Telecom",
    themes: ["telecom", "dividend", "value", "income", "defensive"],
    valuationScore: 72, momentumScore: 40, qualityScore: 62, lowVolScore: 70, profitabilityScore: 62,
    dividendYield: 6.6, dividendGrowth5Y: 2, payoutRatio: 82, beta: 0.4, marketCapB: 176, tier: "large",
    peRatio: 10, revenueGrowthYoY: 1, fcfMargin: 14, grossMargin: 58, roe: 22, debtToEquity: 1.7,
    esgScore: 66, carbonIntensity: "low", country: "US",
  },
  // ─── INDUSTRIALS ─────────────────────────────────────────────────────────
  {
    ticker: "LMT", name: "Lockheed Martin", sector: "Industrials", industry: "Aerospace & Defense",
    themes: ["industrial", "defense", "dividend", "dividend_growth", "value", "low_volatility"],
    valuationScore: 68, momentumScore: 62, qualityScore: 80, lowVolScore: 68, profitabilityScore: 80,
    dividendYield: 2.7, dividendGrowth5Y: 7, payoutRatio: 50, beta: 0.5, marketCapB: 126, tier: "large",
    peRatio: 20, revenueGrowthYoY: 5, fcfMargin: 12, grossMargin: 13, roe: 248, debtToEquity: 0,
    esgScore: 50, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "RTX", name: "RTX Corporation", sector: "Industrials", industry: "Aerospace & Defense",
    themes: ["industrial", "defense", "dividend", "dividend_growth", "value"],
    valuationScore: 66, momentumScore: 64, qualityScore: 78, lowVolScore: 62, profitabilityScore: 76,
    dividendYield: 2.2, dividendGrowth5Y: 6, payoutRatio: 52, beta: 0.7, marketCapB: 140, tier: "large",
    peRatio: 34, revenueGrowthYoY: 10, fcfMargin: 8, grossMargin: 25, roe: 10, debtToEquity: 0.6,
    esgScore: 54, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "HON", name: "Honeywell International", sector: "Industrials", industry: "Conglomerate",
    themes: ["industrial", "dividend", "dividend_growth", "quality", "low_volatility"],
    valuationScore: 62, momentumScore: 54, qualityScore: 82, lowVolScore: 68, profitabilityScore: 80,
    dividendYield: 2.2, dividendGrowth5Y: 7, payoutRatio: 56, beta: 1.0, marketCapB: 136, tier: "large",
    peRatio: 26, revenueGrowthYoY: 3, fcfMargin: 16, grossMargin: 34, roe: 32, debtToEquity: 1.2,
    esgScore: 72, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials", industry: "Heavy Machinery",
    themes: ["industrial", "dividend", "dividend_growth", "value", "low_volatility"],
    valuationScore: 62, momentumScore: 68, qualityScore: 76, lowVolScore: 56, profitabilityScore: 78,
    dividendYield: 1.6, dividendGrowth5Y: 8, payoutRatio: 36, beta: 1.0, marketCapB: 190, tier: "large",
    peRatio: 17, revenueGrowthYoY: -4, fcfMargin: 14, grossMargin: 38, roe: 62, debtToEquity: 2.6,
    esgScore: 60, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "UNP", name: "Union Pacific", sector: "Industrials", industry: "Railroads",
    themes: ["industrial", "dividend", "dividend_growth", "quality", "low_volatility", "value"],
    valuationScore: 64, momentumScore: 60, qualityScore: 82, lowVolScore: 70, profitabilityScore: 82,
    dividendYield: 2.2, dividendGrowth5Y: 10, payoutRatio: 50, beta: 0.85, marketCapB: 146, tier: "large",
    peRatio: 22, revenueGrowthYoY: -1, fcfMargin: 22, grossMargin: 54, roe: 50, debtToEquity: 2.0,
    esgScore: 68, carbonIntensity: "medium", country: "US",
  },
  // ─── CONSUMER DISCRETIONARY ──────────────────────────────────────────────
  {
    ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary", industry: "Electric Vehicles",
    themes: ["clean_energy", "growth", "consumer", "momentum"],
    valuationScore: 36, momentumScore: 76, qualityScore: 68, lowVolScore: 14, profitabilityScore: 66,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 2.3, marketCapB: 792, tier: "mega",
    peRatio: 90, revenueGrowthYoY: -1, fcfMargin: 3, grossMargin: 18, roe: 10, debtToEquity: 0.1,
    esgScore: 56, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "HD", name: "Home Depot Inc.", sector: "Consumer Discretionary", industry: "Home Improvement",
    themes: ["consumer", "dividend", "dividend_growth", "quality", "value", "low_volatility"],
    valuationScore: 60, momentumScore: 62, qualityScore: 86, lowVolScore: 62, profitabilityScore: 84,
    dividendYield: 2.5, dividendGrowth5Y: 11, payoutRatio: 58, beta: 0.95, marketCapB: 354, tier: "mega",
    peRatio: 24, revenueGrowthYoY: -2, fcfMargin: 12, grossMargin: 33, roe: 0, debtToEquity: 0,
    esgScore: 68, carbonIntensity: "medium", country: "US",
  },
  {
    ticker: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary", industry: "Footwear & Apparel",
    themes: ["consumer", "dividend", "dividend_growth", "quality", "brand"],
    valuationScore: 58, momentumScore: 46, qualityScore: 82, lowVolScore: 52, profitabilityScore: 78,
    dividendYield: 2.1, dividendGrowth5Y: 11, payoutRatio: 50, beta: 1.1, marketCapB: 104, tier: "large",
    peRatio: 26, revenueGrowthYoY: -10, fcfMargin: 12, grossMargin: 44, roe: 32, debtToEquity: 0.8,
    esgScore: 72, carbonIntensity: "medium", country: "US",
  },
  // ─── REITS ───────────────────────────────────────────────────────────────
  {
    ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate", industry: "Industrial REITs",
    themes: ["infrastructure", "dividend", "income", "low_volatility"],
    valuationScore: 54, momentumScore: 58, qualityScore: 78, lowVolScore: 64, profitabilityScore: 74,
    dividendYield: 3.2, dividendGrowth5Y: 10, payoutRatio: 72, beta: 0.9, marketCapB: 104, tier: "large",
    peRatio: 38, revenueGrowthYoY: 7, fcfMargin: 32, grossMargin: 74, roe: 8, debtToEquity: 0.6,
    esgScore: 78, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "AMT", name: "American Tower", sector: "Real Estate", industry: "Cell Towers",
    themes: ["infrastructure", "telecom", "dividend", "dividend_growth", "income"],
    valuationScore: 54, momentumScore: 52, qualityScore: 76, lowVolScore: 60, profitabilityScore: 72,
    dividendYield: 3.3, dividendGrowth5Y: 11, payoutRatio: 74, beta: 0.85, marketCapB: 90, tier: "large",
    peRatio: 42, revenueGrowthYoY: 4, fcfMargin: 26, grossMargin: 72, roe: 34, debtToEquity: 3.4,
    esgScore: 70, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "O", name: "Realty Income Corp.", sector: "Real Estate", industry: "Net Lease REITs",
    themes: ["income", "dividend", "dividend_growth", "defensive", "low_volatility"],
    valuationScore: 62, momentumScore: 50, qualityScore: 74, lowVolScore: 72, profitabilityScore: 72,
    dividendYield: 5.8, dividendGrowth5Y: 3, payoutRatio: 82, beta: 0.6, marketCapB: 46, tier: "large",
    peRatio: 50, revenueGrowthYoY: 9, fcfMargin: 26, grossMargin: 68, roe: 3, debtToEquity: 0.9,
    esgScore: 72, carbonIntensity: "very_low", country: "US",
  },
  // ─── ADDITIONAL GROWTH / MOMENTUM ────────────────────────────────────────
  {
    ticker: "NFLX", name: "Netflix Inc.", sector: "Communication Services", industry: "Streaming",
    themes: ["consumer", "growth", "momentum", "quality"],
    valuationScore: 48, momentumScore: 82, qualityScore: 82, lowVolScore: 32, profitabilityScore: 80,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.2, marketCapB: 380, tier: "mega",
    peRatio: 44, revenueGrowthYoY: 16, fcfMargin: 14, grossMargin: 43, roe: 34, debtToEquity: 0.9,
    esgScore: 64, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer Discretionary", industry: "Athletic Apparel",
    themes: ["consumer", "quality", "growth"],
    valuationScore: 56, momentumScore: 56, qualityScore: 84, lowVolScore: 44, profitabilityScore: 82,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.2, marketCapB: 38, tier: "large",
    peRatio: 26, revenueGrowthYoY: 10, fcfMargin: 16, grossMargin: 58, roe: 38, debtToEquity: 0.5,
    esgScore: 68, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "ASML", name: "ASML Holding NV", sector: "Information Technology", industry: "Semiconductor Equipment",
    themes: ["semiconductor", "ai", "infrastructure", "quality", "momentum"],
    valuationScore: 58, momentumScore: 80, qualityScore: 92, lowVolScore: 36, profitabilityScore: 88,
    dividendYield: 0.9, dividendGrowth5Y: 18, payoutRatio: 38, beta: 1.2, marketCapB: 296, tier: "large",
    peRatio: 34, revenueGrowthYoY: 14, fcfMargin: 34, grossMargin: 52, roe: 62, debtToEquity: 0.3,
    esgScore: 78, carbonIntensity: "low", country: "Netherlands",
  },
  {
    ticker: "AMAT", name: "Applied Materials", sector: "Information Technology", industry: "Semiconductor Equipment",
    themes: ["semiconductor", "ai", "infrastructure", "value", "dividend_growth"],
    valuationScore: 68, momentumScore: 76, qualityScore: 84, lowVolScore: 34, profitabilityScore: 82,
    dividendYield: 0.8, dividendGrowth5Y: 12, payoutRatio: 20, beta: 1.35, marketCapB: 160, tier: "large",
    peRatio: 22, revenueGrowthYoY: 7, fcfMargin: 22, grossMargin: 47, roe: 44, debtToEquity: 0.6,
    esgScore: 72, carbonIntensity: "low", country: "US",
  },
  {
    ticker: "CRWD", name: "CrowdStrike Holdings", sector: "Information Technology", industry: "Cybersecurity",
    themes: ["software", "security", "growth", "momentum", "ai"],
    valuationScore: 42, momentumScore: 84, qualityScore: 80, lowVolScore: 28, profitabilityScore: 72,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.3, marketCapB: 94, tier: "large",
    peRatio: 94, revenueGrowthYoY: 29, fcfMargin: 28, grossMargin: 76, roe: 18, debtToEquity: 0.4,
    esgScore: 70, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "WDAY", name: "Workday Inc.", sector: "Information Technology", industry: "HCM Software",
    themes: ["software", "cloud", "quality"],
    valuationScore: 50, momentumScore: 66, qualityScore: 80, lowVolScore: 40, profitabilityScore: 76,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.15, marketCapB: 60, tier: "large",
    peRatio: 50, revenueGrowthYoY: 15, fcfMargin: 22, grossMargin: 76, roe: 10, debtToEquity: 0.4,
    esgScore: 74, carbonIntensity: "very_low", country: "US",
  },
  {
    ticker: "SHOP", name: "Shopify Inc.", sector: "Information Technology", industry: "E-Commerce Platform",
    themes: ["fintech", "software", "growth", "momentum", "consumer"],
    valuationScore: 44, momentumScore: 78, qualityScore: 76, lowVolScore: 24, profitabilityScore: 68,
    dividendYield: 0, dividendGrowth5Y: 0, payoutRatio: 0, beta: 1.6, marketCapB: 128, tier: "large",
    peRatio: 80, revenueGrowthYoY: 24, fcfMargin: 16, grossMargin: 50, roe: 6, debtToEquity: 0.1,
    esgScore: 66, carbonIntensity: "very_low", country: "US",
  },
];
